<?php

$data = [
  0 => [
    'First Name' => 'Naomi',
    'Last Name' => 'Tucker',
    'Gender' => 'Female',
    'Age' => '22',
    'Years' => '7',
  ],
  1 => [
    'First Name' => 'Frederick',
    'Last Name' => 'Crawford',
    'Gender' => 'Male',
    'Age' => '20',
    'Years' => '3',
  ],
  2 => [
    'First Name' => 'Jessica',
    'Last Name' => 'Hall',
    'Gender' => 'Female',
    'Age' => '27',
    'Years' => '8',
  ],
  3 => [
    'First Name' => 'Agata',
    'Last Name' => 'Thompson',
    'Gender' => 'Female',
    'Age' => '24',
    'Years' => '7',
  ],
  4 => [
    'First Name' => 'Eleanor',
    'Last Name' => 'Owens',
    'Gender' => 'Female',
    'Age' => '18',
    'Years' => '4',
  ],
  5 => [
    'First Name' => 'Alen',
    'Last Name' => 'Moore',
    'Gender' => 'Male',
    'Age' => '28',
    'Years' => '2',
  ],
  6 => [
    'First Name' => 'Blake',
    'Last Name' => 'Harper',
    'Gender' => 'Male',
    'Age' => '28',
    'Years' => '7',
  ],
  7 => [
    'First Name' => 'Lucy',
    'Last Name' => 'Lloyd',
    'Gender' => 'Female',
    'Age' => '22',
    'Years' => '1',
  ],
  8 => [
    'First Name' => 'Alina',
    'Last Name' => 'Owens',
    'Gender' => 'Female',
    'Age' => '19',
    'Years' => '5',
  ],
  9 => [
    'First Name' => 'Michelle',
    'Last Name' => 'Holmes',
    'Gender' => 'Female',
    'Age' => '26',
    'Years' => '5',
  ],
  10 => [
    'First Name' => 'Oscar',
    'Last Name' => 'West',
    'Gender' => 'Male',
    'Age' => '28',
    'Years' => '3',
  ],
  11 => [
    'First Name' => 'Amanda',
    'Last Name' => 'Warren',
    'Gender' => 'Female',
    'Age' => '25',
    'Years' => '7',
  ],
  12 => [
    'First Name' => 'Stuart',
    'Last Name' => 'Smith',
    'Gender' => 'Male',
    'Age' => '25',
    'Years' => '3',
  ],
  13 => [
    'First Name' => 'Justin',
    'Last Name' => 'Wilson',
    'Gender' => 'Male',
    'Age' => '19',
    'Years' => '3',
  ],
  14 => [
    'First Name' => 'Henry',
    'Last Name' => 'Crawford',
    'Gender' => 'Male',
    'Age' => '22',
    'Years' => '1',
  ],
  15 => [
    'First Name' => 'Marcus',
    'Last Name' => 'Ross',
    'Gender' => 'Male',
    'Age' => '24',
    'Years' => '5',
  ],
  16 => [
    'First Name' => 'Dominik',
    'Last Name' => 'Holmes',
    'Gender' => 'Male',
    'Age' => '22',
    'Years' => '0',
  ],
  17 => [
    'First Name' => 'Richard',
    'Last Name' => 'Cole',
    'Gender' => 'Male',
    'Age' => '25',
    'Years' => '9',
  ],
  18 => [
    'First Name' => 'Honey',
    'Last Name' => 'Miller',
    'Gender' => 'Female',
    'Age' => '27',
    'Years' => '9',
  ],
  19 => [
    'First Name' => 'Jessica',
    'Last Name' => 'Parker',
    'Gender' => 'Female',
    'Age' => '30',
    'Years' => '0',
  ],
  20 => [
    'First Name' => 'Carina',
    'Last Name' => 'Foster',
    'Gender' => 'Female',
    'Age' => '19',
    'Years' => '0',
  ],
  21 => [
    'First Name' => 'Naomi',
    'Last Name' => 'Mason',
    'Gender' => 'Female',
    'Age' => '27',
    'Years' => '6',
  ],
  22 => [
    'First Name' => 'Joyce',
    'Last Name' => 'Cunningham',
    'Gender' => 'Female',
    'Age' => '25',
    'Years' => '7',
  ],
  23 => [
    'First Name' => 'Tiana',
    'Last Name' => 'Mitchell',
    'Gender' => 'Female',
    'Age' => '27',
    'Years' => '0',
  ],
  24 => [
    'First Name' => 'Elise',
    'Last Name' => 'Mason',
    'Gender' => 'Female',
    'Age' => '28',
    'Years' => '2',
  ],
  25 => [
    'First Name' => 'David',
    'Last Name' => 'Davis',
    'Gender' => 'Male',
    'Age' => '25',
    'Years' => '2',
  ],
  26 => [
    'First Name' => 'Robert',
    'Last Name' => 'Wilson',
    'Gender' => 'Male',
    'Age' => '28',
    'Years' => '0',
  ],
  27 => [
    'First Name' => 'Alexander',
    'Last Name' => 'Spencer',
    'Gender' => 'Male',
    'Age' => '20',
    'Years' => '2',
  ],
  28 => [
    'First Name' => 'Adison',
    'Last Name' => 'Hamilton',
    'Gender' => 'Male',
    'Age' => '23',
    'Years' => '3',
  ],
  29 => [
    'First Name' => 'Justin',
    'Last Name' => 'Owens',
    'Gender' => 'Male',
    'Age' => '27',
    'Years' => '6',
  ],
  30 => [
    'First Name' => 'Stuart',
    'Last Name' => 'Morrison',
    'Gender' => 'Male',
    'Age' => '24',
    'Years' => '3',
  ],
  31 => [
    'First Name' => 'Amber',
    'Last Name' => 'Perkins',
    'Gender' => 'Female',
    'Age' => '20',
    'Years' => '1',
  ],
  32 => [
    'First Name' => 'Florrie',
    'Last Name' => 'Perkins',
    'Gender' => 'Female',
    'Age' => '28',
    'Years' => '1',
  ],
  33 => [
    'First Name' => 'Edwin',
    'Last Name' => 'Montgomery',
    'Gender' => 'Male',
    'Age' => '18',
    'Years' => '4',
  ],
  34 => [
    'First Name' => 'Edith',
    'Last Name' => 'Douglas',
    'Gender' => 'Female',
    'Age' => '23',
    'Years' => '2',
  ],
  35 => [
    'First Name' => 'Lucas',
    'Last Name' => 'Douglas',
    'Gender' => 'Male',
    'Age' => '21',
    'Years' => '9',
  ],
  36 => [
    'First Name' => 'Sienna',
    'Last Name' => 'Chapman',
    'Gender' => 'Female',
    'Age' => '30',
    'Years' => '4',
  ],
  37 => [
    'First Name' => 'Ashton',
    'Last Name' => 'Mitchell',
    'Gender' => 'Male',
    'Age' => '20',
    'Years' => '0',
  ],
  38 => [
    'First Name' => 'Chloe',
    'Last Name' => 'Evans',
    'Gender' => 'Female',
    'Age' => '24',
    'Years' => '0',
  ],
  39 => [
    'First Name' => 'Lenny',
    'Last Name' => 'Armstrong',
    'Gender' => 'Male',
    'Age' => '21',
    'Years' => '7',
  ],
  40 => [
    'First Name' => 'Belinda',
    'Last Name' => 'Henderson',
    'Gender' => 'Female',
    'Age' => '21',
    'Years' => '0',
  ],
  41 => [
    'First Name' => 'Michael',
    'Last Name' => 'Ferguson',
    'Gender' => 'Male',
    'Age' => '20',
    'Years' => '7',
  ],
  42 => [
    'First Name' => 'Sabrina',
    'Last Name' => 'Wells',
    'Gender' => 'Female',
    'Age' => '24',
    'Years' => '6',
  ],
  43 => [
    'First Name' => 'Albert',
    'Last Name' => 'Clark',
    'Gender' => 'Male',
    'Age' => '26',
    'Years' => '8',
  ],
  44 => [
    'First Name' => 'Ryan',
    'Last Name' => 'Murray',
    'Gender' => 'Male',
    'Age' => '19',
    'Years' => '2',
  ],
  45 => [
    'First Name' => 'Julia',
    'Last Name' => 'Clark',
    'Gender' => 'Female',
    'Age' => '27',
    'Years' => '2',
  ],
  46 => [
    'First Name' => 'Mary',
    'Last Name' => 'Robinson',
    'Gender' => 'Female',
    'Age' => '21',
    'Years' => '3',
  ],
  47 => [
    'First Name' => 'Sofia',
    'Last Name' => 'Bailey',
    'Gender' => 'Female',
    'Age' => '24',
    'Years' => '7',
  ],
  48 => [
    'First Name' => 'Derek',
    'Last Name' => 'Wright',
    'Gender' => 'Male',
    'Age' => '24',
    'Years' => '4',
  ],
  49 => [
    'First Name' => 'Emma',
    'Last Name' => 'Roberts',
    'Gender' => 'Female',
    'Age' => '21',
    'Years' => '5',
  ],
];
